# This is a basic workflow to help you get started with Actions
name: 'TestingDevlop pull request check'

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master, staging, develop, TestingDevlop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install Salesforce CLI
      - name: 'Build and Deploy'
        run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
            ./sfdx-cli/install
                          
      # TestConfluence
      - name: Read TestConfluence
        id: testconfluence
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/TestConfluence.txt
          trim: true
      
      # Print TestConfluence content
      - name: Echo package.json
        run: echo "${{steps.testconfluence.outputs.content}} $GITHUB_REF $GITHUB_BASE_REF"  
